site_name: BDR ABIS Mapping
site_url: https://gaiaresources.github.io/abis-mappping/
theme:
  name: material
docs_dir: docs/pages
extra:
  version:
    provider: mike
plugins:
  - mike:
      canonical_version: latest
      version_selector: true
strict: true
validation:
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
