site_name: BDR ABIS Mapping
site_url: https://gaiaresources.github.io/abis-mappping/
repo_url: https://github.com/gaiaresources/abis-mapping/
repo_name: gaiaresources/abis-mapping
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate
    - navigation.indexes
docs_dir: docs/pages
extra:
  version:
    provider: mike
plugins:
  - mike:
      canonical_version: latest
      version_selector: true
strict: true
validation:
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
markdown_extensions:
  - admonition
