[tool.poetry]
name = "abis-mapping"
version = "4.2.1"
description = "Provides templates and mappings to translate tabular data to ABIS rdf"
authors = ["Gaia Resources <dev@gaiaresources.com.au>"]

[tool.poetry.dependencies]
python = "^3.11"
rdflib = "^7.0.0"
python-slugify = "^8.0.1"
frictionless = {extras = ["excel"], version = "^5.16.0"}
python-dateutil = "^2.8.2"
shapely = "^2.0.2"
pyproj = "^3.6.1"

[tool.poetry.group.dev.dependencies]
mypy = "^0.942"
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
types-python-dateutil = "^2.8.16"
types-python-slugify = "^8.0.0.3"
pytest-mock = "^3.12.0"
pandas = "^2.1.4"
pyshacl = "^0.25.0"
pydantic = "^2.4.2"
jinja2 = "^3.1.4"
mkdocs-material = "^9.5.27"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
