[tool.poetry]
name = "abis-mapping"
version = "4.2.3"
description = "Provides templates and mappings to translate tabular data to ABIS rdf"
authors = ["Gaia Resources <dev@gaiaresources.com.au>"]

[tool.poetry.dependencies]
python = "^3.11"
rdflib = "^7.0.0"
python-slugify = "^8.0.1"
frictionless = {extras = ["excel"], version = "^5.16.0"}
python-dateutil = "^2.8.2"
shapely = "^2.0.2"
pyproj = "^3.6.1"
pydantic = "^2.4.2"
pydantic-settings = "^2.4.0"
poethepoet = "^0.29.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
mypy = "^1.11.1"
types-python-dateutil = "^2.8.16"
types-python-slugify = "^8.0.0.3"
ruff = "^0.6.8"
pandas = "^2.1.4"
pyshacl = "^0.25.0"
jinja2 = "^3.1.4"
mkdocs-material = "^9.5.27"
mike = "^2.1.3"

[tool.poe.tasks]
lint = "ruff check"
lint-fix = "ruff check --fix-only"
format = "ruff format"
format-check = "ruff format --check"
typecheck = "mypy tests/ abis_mapping/ docs/"
generate-instructions = "./scripts/generate_instructions.sh"
test = "pytest tests --cov=abis_mapping --cov=docs --cov-report=term-missing"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = [
    # Default rules
    "E4", "E7", "E9", "F",
    # additional rules
    "B",  # bugbear
    "A",  # builtins
    "S",  # bandit
    "G",  # logging-format
]

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py for re-exporting
"__init__.py" = ["F401"]
# Allow using assert in tests
"tests/*" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"
