[tool.poetry]
name = "abis-mapping"
version = "2.2.0"
description = "Provides templates and mappings to translate tabular data to ABIS rdf"
authors = ["Gaia Resources <dev@gaiaresources.com.au>"]

[tool.poetry.dependencies]
python = "^3.11"
rdflib = "^7.0.0"
python-slugify = "^8.0.1"
frictionless = {extras = ["excel"], version = "^5.16.0"}
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
mypy = "^0.942"
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
types-python-dateutil = "^2.8.16"

[tool.poetry.group.dev.dependencies]
types-python-slugify = "^8.0.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
