name: release
on:
  release:
    types:
      - published
      - deleted
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs-site
        uses: actions/checkout@v4
        with:
          ref: docs-site
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Project and Generate Markdown
        run: |
          pipx install poetry==1.6.1
          poetry install
          poetry run bash scripts/generate_instructions.sh
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build Site
        run: |
          if [ "${{ github.event.action }}" == "published" ]; then
            echo "creating site version ${{ github.ref_name }}"
            poetry run mike deploy --push --branch=docs-site --update-aliases ${{ github.ref_name }} latest 
            poetry run mike set-default --push latest
          elif [ "${{ github.event.action }}" == "deleted" ]; then
            poetry run mike delete --push $GITHUB_REF_NAME
          fi
