name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-and-dependencies
        with:
          python-version: "3.11"
      - run: poetry run poe format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-and-dependencies
        with:
          python-version: "3.11"
      - run: poetry run poe lint

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-and-dependencies
        with:
          python-version: "3.11"
      - run: poetry run poe typecheck

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-and-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run poe test
